//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StaticValues", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the disclaimer.
        /// </summary>
        internal static string Student_agree_to_disclaimer {
            get {
                return ResourceManager.GetString("Student_agree_to_disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  There was a problem sending you an email.  Please print this page for your records..
        /// </summary>
        internal static string Student_Email_Problem {
            get {
                return ResourceManager.GetString("Student_Email_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student has multiple majors but did not supply a major code..
        /// </summary>
        internal static string Student_Major_Code_Not_Supplied {
            get {
                return ResourceManager.GetString("Student_Major_Code_Not_Supplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching ceremony found.  Please try your registration again..
        /// </summary>
        internal static string Student_No_Ceremony_Found {
            get {
                return ResourceManager.GetString("Student_No_Ceremony_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered for commencement..
        /// </summary>
        internal static string Student_Register_Successful {
            get {
                return ResourceManager.GetString("Student_Register_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Confirmation.
        /// </summary>
        internal static string Template_RegistrationConfirmation {
            get {
                return ResourceManager.GetString("Template_RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Petition.
        /// </summary>
        internal static string Template_RegistrationPetition {
            get {
                return ResourceManager.GetString("Template_RegistrationPetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Petition - Approved.
        /// </summary>
        internal static string Template_RegistrationPetition_Approved {
            get {
                return ResourceManager.GetString("Template_RegistrationPetition_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Petition.
        /// </summary>
        internal static string Template_TicketPetition {
            get {
                return ResourceManager.GetString("Template_TicketPetition", resourceCulture);
            }
        }
    }
}
