//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commencement.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticIndexes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticIndexes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commencement.Core.Resources.StaticIndexes", typeof(StaticIndexes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentStudent.
        /// </summary>
        public static string CurrentStudentKey {
            get {
                return ResourceManager.GetString("CurrentStudentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentTerm.
        /// </summary>
        public static string CurrentTermKey {
            get {
                return ResourceManager.GetString("CurrentTermKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulation.
        /// </summary>
        public static string EmulationKey {
            get {
                return ResourceManager.GetString("EmulationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ML.
        /// </summary>
        public static string Td_Mail {
            get {
                return ResourceManager.GetString("Td_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PU.
        /// </summary>
        public static string Td_Pickup {
            get {
                return ResourceManager.GetString("Td_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCeremonies.
        /// </summary>
        public static string UserCeremoniesKey {
            get {
                return ResourceManager.GetString("UserCeremoniesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCeremonyIds.
        /// </summary>
        public static string UserCeremonyIdsKey {
            get {
                return ResourceManager.GetString("UserCeremonyIdsKey", resourceCulture);
            }
        }
    }
}
