ALTER TABLE [dbo].[GeVersions]
    ADD CONSTRAINT [PK_GeVersions_1] PRIMARY KEY CLUSTERED ([Version] ASC, [GeSubjectAreaCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

