ALTER TABLE [dbo].[StudentTerms]
    ADD CONSTRAINT [PK_StudentTerms] PRIMARY KEY CLUSTERED ([PIDM] ASC, [TermCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

