ALTER TABLE [dbo].[Waitlist]
    ADD CONSTRAINT [PK_Waitlist] PRIMARY KEY CLUSTERED ([PIDM] ASC, [Termcode] ASC, [CRN] ASC, [DateTaken] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

