insert into states (name,abbreviation) values ('ALABAMA','AL');
insert into states (name,abbreviation) values ('ALASKA ','AK');
insert into states (name,abbreviation) values ('ARIZONA','AZ');
insert into states (name,abbreviation) values ('ARKANSAS','AR');
insert into states (name,abbreviation) values ('CALIFORNIA','CA');
insert into states (name,abbreviation) values ('COLORADO','CO');
insert into states (name,abbreviation) values ('CONNECTICUT','CT');
insert into states (name,abbreviation) values ('DELAWARE','DE');
insert into states (name,abbreviation) values ('DISTRICT OF COLUMBIA','DC');
insert into states (name,abbreviation) values ('FLORIDA','FL');
insert into states (name,abbreviation) values ('GEORGIA','GA');
insert into states (name,abbreviation) values ('HAWAII ','HI');
insert into states (name,abbreviation) values ('IDAHO','ID');
insert into states (name,abbreviation) values ('ILLINOIS','IL');
insert into states (name,abbreviation) values ('INDIANA','IN');
insert into states (name,abbreviation) values ('IOWA','IA');
insert into states (name,abbreviation) values ('KANSAS ','KS');
insert into states (name,abbreviation) values ('KENTUCKY','KY');
insert into states (name,abbreviation) values ('LOUISIANA','LA');
insert into states (name,abbreviation) values ('MAINE','ME');
insert into states (name,abbreviation) values ('MARYLAND','MD');
insert into states (name,abbreviation) values ('MASSACHUSETTS','MA');
insert into states (name,abbreviation) values ('MICHIGAN','MI');
insert into states (name,abbreviation) values ('MINNESOTA','MN');
insert into states (name,abbreviation) values ('MISSISSIPPI','MS');
insert into states (name,abbreviation) values ('MISSOURI','MO');
insert into states (name,abbreviation) values ('MONTANA','MT');
insert into states (name,abbreviation) values ('NEBRASKA','NE');
insert into states (name,abbreviation) values ('NEVADA ','NV');
insert into states (name,abbreviation) values ('NEW HAMPSHIRE','NH');
insert into states (name,abbreviation) values ('NEW JERSEY','NJ');
insert into states (name,abbreviation) values ('NEW MEXICO','NM');
insert into states (name,abbreviation) values ('NEW YORK','NY');
insert into states (name,abbreviation) values ('NORTH CAROLINA','NC');
insert into states (name,abbreviation) values ('NORTH DAKOTA','ND');
insert into states (name,abbreviation) values ('OHIO','OH');
insert into states (name,abbreviation) values ('OKLAHOMA','OK');
insert into states (name,abbreviation) values ('OREGON ','OR');
insert into states (name,abbreviation) values ('PENNSYLVANIA','PA');
insert into states (name,abbreviation) values ('PUERTO RICO','PR');
insert into states (name,abbreviation) values ('RHODE ISLAND','RI');
insert into states (name,abbreviation) values ('SOUTH CAROLINA','SC');
insert into states (name,abbreviation) values ('SOUTH DAKOTA','SD');
insert into states (name,abbreviation) values ('TENNESSEE','TN');
insert into states (name,abbreviation) values ('TEXAS','TX');
insert into states (name,abbreviation) values ('UTAH','UT');
insert into states (name,abbreviation) values ('VERMONT','VT');
insert into states (name,abbreviation) values ('U.S. VIRGIN ISLANDS','VI');
insert into states (name,abbreviation) values ('VIRGINIA','VA');
insert into states (name,abbreviation) values ('WASHINGTON','WA');
insert into states (name,abbreviation) values ('WEST VIRGINIA','WV');
insert into states (name,abbreviation) values ('WISCONSIN','WI');
insert into states (name,abbreviation) values ('WYOMING','WY'); 