ALTER TABLE [dbo].[CeremonyMajors]
    ADD CONSTRAINT [PK_CommencementMajors] PRIMARY KEY CLUSTERED ([CeremonyId] ASC, [MajorCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

