ALTER TABLE [dbo].[RegistrationSpecialNeeds]
    ADD CONSTRAINT [PK_RegistrationSpecialNeeds] PRIMARY KEY CLUSTERED ([SpecialNeedId] ASC, [RegistrationId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

