SET IDENTITY_INSERT [dbo].[TemplateTokens] ON
GO

insert into templatetokens(id, templatetypeid, name) values (1, 1, 'Student Id')
insert into templatetokens(id, templatetypeid, name) values (2, 1, 'Student Name')
insert into templatetokens(id, templatetypeid, name) values (3, 1, 'Ceremony Name')
insert into templatetokens(id, templatetypeid, name) values (4, 1, 'Ceremony Time')
insert into templatetokens(id, templatetypeid, name) values (5, 1, 'Ceremony Location')
insert into templatetokens(id, templatetypeid, name) values (6, 1, 'Number Of Tickets')
insert into templatetokens(id, templatetypeid, name) values (7, 1, 'Address Line 1')
insert into templatetokens(id, templatetypeid, name) values (8, 1, 'Address Line 2')
insert into templatetokens(id, templatetypeid, name) values (9, 1, 'City')
insert into templatetokens(id, templatetypeid, name) values (10, 1, 'State')
insert into templatetokens(id, templatetypeid, name) values (11, 1, 'Zip')
insert into templatetokens(id, templatetypeid, name) values (12, 1, 'Distribution Method')
insert into templatetokens(id, templatetypeid, name) values (13, 1, 'SpecialNeeds')
insert into templatetokens(id, templatetypeid, name) values (14, 1, 'Major')
insert into templatetokens(id, templatetypeid, name) values (15, 1, 'Status')
insert into templatetokens(id, templatetypeid, name) values (16, 2, 'Student Id')
insert into templatetokens(id, templatetypeid, name) values (17, 2, 'Student Name')
insert into templatetokens(id, templatetypeid, name) values (18, 2, 'Exception Reason')
insert into templatetokens(id, templatetypeid, name) values (19, 2, 'Completion Term')
insert into templatetokens(id, templatetypeid, name) values (20, 2, 'Ceremony Name')
insert into templatetokens(id, templatetypeid, name) values (21, 2, 'Ceremony Time')
insert into templatetokens(id, templatetypeid, name) values (22, 2, 'Ceremony Location')
insert into templatetokens(id, templatetypeid, name) values (23, 2, 'Number Of Tickets')
insert into templatetokens(id, templatetypeid, name) values (24, 2, 'Address Line 1')
insert into templatetokens(id, templatetypeid, name) values (25, 2, 'Address Line 2')
insert into templatetokens(id, templatetypeid, name) values (26, 2, 'City')
insert into templatetokens(id, templatetypeid, name) values (27, 2, 'State')
insert into templatetokens(id, templatetypeid, name) values (28, 2, 'Zip')
insert into templatetokens(id, templatetypeid, name) values (29, 2, 'Distribution Method')
insert into templatetokens(id, templatetypeid, name) values (30, 2, 'SpecialNeeds')
insert into templatetokens(id, templatetypeid, name) values (31, 2, 'Major')
insert into templatetokens(id, templatetypeid, name) values (32, 2, 'Status')
insert into templatetokens(id, templatetypeid, name) values (33, 3, 'Student Id')
insert into templatetokens(id, templatetypeid, name) values (34, 3, 'Student Name')
insert into templatetokens(id, templatetypeid, name) values (35, 3, 'Ceremony Name')
insert into templatetokens(id, templatetypeid, name) values (36, 3, 'Ceremony Time')
insert into templatetokens(id, templatetypeid, name) values (37, 3, 'Ceremony Location')
insert into templatetokens(id, templatetypeid, name) values (38, 3, 'Number Of Tickets')
insert into templatetokens(id, templatetypeid, name) values (39, 3, 'Address Line 1')
insert into templatetokens(id, templatetypeid, name) values (40, 3, 'Address Line 2')
insert into templatetokens(id, templatetypeid, name) values (41, 3, 'City')
insert into templatetokens(id, templatetypeid, name) values (42, 3, 'State')
insert into templatetokens(id, templatetypeid, name) values (43, 3, 'Zip')
insert into templatetokens(id, templatetypeid, name) values (44, 3, 'Distribution Method')
insert into templatetokens(id, templatetypeid, name) values (45, 3, 'SpecialNeeds')
insert into templatetokens(id, templatetypeid, name) values (46, 3, 'Major')
insert into templatetokens(id, templatetypeid, name) values (47, 3, 'Number Of Extra Tickets')
insert into templatetokens(id, templatetypeid, name) values (48, 3, 'Status')
insert into templatetokens(id, templatetypeid, name) values (49, 3, 'Number Streaming Tickets')
insert into templatetokens(id, templatetypeid, name) values (50, 4, 'Student Id')
insert into templatetokens(id, templatetypeid, name) values (51, 4, 'Student Name')
insert into templatetokens(id, templatetypeid, name) values (52, 4, 'Exception Reason')
insert into templatetokens(id, templatetypeid, name) values (53, 4, 'Completion Term')
insert into templatetokens(id, templatetypeid, name) values (54, 4, 'Petition Decision')

SET IDENTITY_INSERT [dbo].[TemplateTokens] OFF
GO